[package]
name = "pentest_copilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.24"
quick-xml = { version = "0.23.0", features = ["serialize"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
anyhow = "1.0"
glob = "0.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
pulldown-cmark = "0.8"
colored = "2.0"

# Binary
[[bin]]
name = "pentest_copilot"
path = "src/main.rs"

# Library
[lib]
name = "pentest_copilot"
path = "src/lib.rs"


[dev-dependencies]
mockall = "0.10.2"
