title: Pentest Copilot Docs
baseurl: "/pentest_copilot"
permalink: pretty
markdown: kramdown
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed


just_the_docs:
  aux_links:
    "Source on GitHub": "https://github.com/fancyc-bsi/pentest_copilot"
  search_enabled: true
  search_label: 'Search the docs...'