title: Your Project Documentation
baseurl: "/pentest_copilot"  # Change 'repository-name' to your GitHub repository name
permalink: pretty
markdown: kramdown
theme: minima  # Or any other theme you prefer

# Plugins
plugins:
  - jekyll-feed
